### ISSUE TITLE
Warning on setup

### ISSUE THREAD

**Issue by Bolukan** [beegee-tokyo/DHTesp#12]
I get the compile-warning:
`warning: 'void DHTesp::setup(uint8_t, DHTesp::DHT_MODEL_t)' is deprecated`
if using
`dht.setup(5, DHTesp::AM2302);`

I guess `__attribute__((deprecated));` belongs to line [123](https://github.com/beegee-tokyo/DHTesp/blob/master/DHTesp.h#L123) in stead of [124](https://github.com/beegee-tokyo/DHTesp/blob/master/DHTesp.h#L124)?

**Comment by beegee-tokyo** [comment]
Correct, thanks for pointing to my mistake. Will correct it.

**Comment by beegee-tokyo** [comment]
Fixed with latest verion
