### ISSUE TITLE
Ticker-ESP32 merged into core

### ISSUE THREAD

**Issue by stritti** [beegee-tokyo/DHTesp#14]
https://github.com/beegee-tokyo/DHTesp/blob/1feec8159cbf9224cdb46f45f57306bcab30c819/examples/DHT_ESP32/DHT_ESP32.ino#L16

This Ticker library has just been merged into the Arduino core for ESP32. See: 
https://github.com/bertmelis/Ticker-esp32

**Comment by beegee-tokyo** [comment]
I know. Just didn't have time to update the examples.
