### ISSUE TITLE
esp8266 example returning null for all fields

### ISSUE THREAD

**Issue by Octavian-the-ent** [beegee-tokyo/DHTesp#17]
I also can't get the functions [described here ](https://desire.giesecke.tk/index.php/2018/01/30/esp32-dht11/) to work correctly.

**Comment by Octavian-the-ent** [comment]
Actually returning Timeout as the status, and then "nan" for every field

**Comment by beegee-tokyo** [comment]
Sounds like a HW problem.
Did you try the sensor on an Arduino board or any other board to confirm it works?
Did you try another sensor?
Is the pullup resistor inside the sensor or external?
What value is the pullup sensor?
Did you measure all connections to make sure they are ok?
What board do you use? ESP32 or ESP8266?
What GPIO pin are you using?

**Comment by Octavian-the-ent** [comment]
Ah, just a simple issue with my pin. My apologies!

**Comment by beegee-tokyo** [comment]
I thought so.
