### ISSUE TITLE
TashHandle_t throwing error "not declared in this scope". 

### ISSUE THREAD

**Issue by Octavian-the-ent** [beegee-tokyo/DHTesp#18]
Examples included with library working beautifully, but trying to follow [this guide](https://desire.giesecke.tk/index.php/2018/01/30/esp32-dht11/) so I can send sensor data over wifi and getting an error on TaskHandle_t object.

**Comment by beegee-tokyo** [comment]
Without seeing your code I cannot tell you whats wrong.
From the title of issue `TashHandle_t` should be `TaskHandle_t`. So maybe just a typo?

**Comment by beegee-tokyo** [comment]
As you didn't update this issue I guess it is solved.
