### ISSUE TITLE
Using this library stops Serial1 on ESP8266

### ISSUE THREAD

**Issue by saloid** [beegee-tokyo/DHTesp#19]
When I am trying to read any data from DHT sensor (getHumidity() or getTemperature() ) i no longer see any messages sent via Serial1 port on ESP8266. After this program still working and data from DHT sensor (AM2302) reads correctly (i receiving mqtt messages).

**Comment by beegee-tokyo** [comment]
The library doesn't use anything related to Serial1 so I do not understand what might cause your problem.
With what GPIO are you initializing the DHT library. Serial1 TX is GPIO2 so you should not use 
`dht.setup(2);`

**Comment by saloid** [comment]
Oh, sorry, i have really used this pin for both functions.
