### ISSUE TITLE
Problems to assign the right pin

### ISSUE THREAD

**Issue by MachmaHinne** [beegee-tokyo/DHTesp#20]
Hi,

I do have problems to get it run with a wemos d1 mini, I think it is a problem with assigning the right pin#.
The docs suggest, that the GPIO# is meant?
By using the diagrams from this documentation
https://escapequotes.net/esp8266-wemos-d1-mini-pins-and-diagram/
means that the value  "5" (GPIO) has to be used, if the DHT22 is connected to Pin D1?
Thank you

Peter

**Comment by beegee-tokyo** [comment]
Glad you solved it.
The different names for GPIOs (specially on the Wemos boards) is confusing.
