### ISSUE TITLE
Humidity values ESP32

### ISSUE THREAD

**Issue by Pythonaire** [beegee-tokyo/DHTesp#22]
Messing around over weeks with value conversion ...
I want to connect an ESP32 to the apple homekit, using the Kolban BLE libraries as you. The homekit expect "float" values for humidity. I tested different versions of value definitions on the ESP, starting with a simple input value "20": doubles, floats, conversion float to std::string, the BLE2904 descriptor with FORMAT_FLOAT32, your version with buffering and bit shifting ... no luck. Got alway null. Im confused what's wrong. it seems the homekit don't accept my values and interpret it as null. Do you have some hints or tips for me?

**Comment by beegee-tokyo** [comment]
Float on BLE is a nightmare.
BLE number formats are shown [here](https://www.bluetooth.com/specifications/assigned-numbers/format-types) which led me through a search for `IEEE-11073 32-bit FLOAT documentation` to [Nordic website](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v12.0.0%2Fstructieee__float32__t.html) which gives some info about the format. 
Maybe that helps.
