### ISSUE TITLE
DHT11 supports one decimal number

### ISSUE THREAD

**Issue by drsnacek** [beegee-tokyo/DHTesp#27]
I tried to use new DHT11 (small board with LED). The DHT.h library shows me one decimal number like 24,5 C. This number is really changing (24,8 or 25,1 etc.) But your library DHTesp.h doesn't show any decimal number - like 24,0 C or 25,0 C  with 0 always.

**Comment by beegee-tokyo** [comment]
The resolution of the Dht11 is 1 deg C according to the datasheet, not 0.1 deg C. I don't know how this other library gets the values with an decimal number.
