### ISSUE TITLE
Full example - Arduino, DHT22

### ISSUE THREAD

**Issue by Eldenroot** [beegee-tokyo/DHTesp#41]
Hi, can I ask you kindly to make a full working example withh al features (calculations) for DHT22 and Arduino?

Thx

**Comment by beegee-tokyo** [comment]
[DHT_ESP32.ino](https://github.com/beegee-tokyo/DHTesp/blob/master/examples/DHT_ESP32/DHT_ESP32.ino) has nearly all functions. Only
**`computePerception()`** and **`computeAbsoluteHumidity()`** are missing.
