### ISSUE TITLE
Wrong humidity shown from DHT_ESP32.ino

### ISSUE THREAD

**Issue by o-bri** [beegee-tokyo/DHTesp#42]
I get a wrong number for the humidity in the example DHT_ESP32.ino

It shows numbers about 9-10 % which is wrong. I used the adafruit DHT22 library to compare, this one gets me plausible results of about 60% - this is what another device also shows to me.

The shown temperature is right and the same is shown with adafruit library and my simple Thermometer device.

Perhaps you can have a look at it. I used your example without any changes.

I use an ESP32 board (Heltec Wifi Kit 32) and DHT22.

Edit:
I tried to use your library in an easier way than in the example.
I do not use the Ticker and Multitasking things.

With just reading with:
  float h = dht.readHumidity();
  float t = dht.readTemperature();

I get the correct results. Does this also work without issues, or do I have to use the "xTaskCreatePinnedToCore" to not get errors while reading the sensors?

**Comment by beegee-tokyo** [comment]
Using an extra task and "xTaskCreatePinnedToCore" depends on your application.

If it works without it for you by just using
```cpp
float h = dht.readHumidity();
float t = dht.readTemperature();
```
then go with that.
